export const GET_PROMOTION_TABLE_REQUEST = 'GET_PROMOTION_TABLE_REQUEST'
export const GET_PROMOTION_TABLE_SUCCESS = 'GET_PROMOTION_TABLE_SUCCESS'
export const GET_PROMOTION_TABLE_FAILURE = 'GET_PROMOTION_TABLE_FAILURE'

export const GET_CHARTBRAND_DATA_REQUEST = 'GET_CHARTBRAND_DATA_REQUEST'
export const GET_CHARTBRAND_DATA_SUCCESS = 'GET_CHARTBRAND_DATA_SUCCESS'
export const GET_CHARTBRAND_DATA_FAILURE = 'GET_CHARTBRAND_DATA_FAILURE'