export const GET_GEOLOCATION_TABLE_REQUEST = 'GET_GEOLOCATION_TABLE_REQUEST'
export const GET_GEOLOCATION_TABLE_SUCCESS = 'GET_GEOLOCATION_TABLE_SUCCESS'
export const GET_GEOLOCATION_TABLE_FAILURE = 'GET_GEOLOCATION_TABLE_FAILURE'

export const GET_GEOLOCATION_MAPD_REQUEST = 'GET_GEOLOCATION_MAPD_REQUEST'
export const GET_GEOLOCATION_MAPD_SUCCESS = 'GET_GEOLOCATION_MAPD_SUCCESS'
export const GET_GEOLOCATION_MAPD_FAILURE = 'GET_GEOLOCATION_MAPD_FAILURE'

export const GET_GEOLOCATION_MAPP_REQUEST = 'GET_GEOLOCATION_MAPP_REQUEST'
export const GET_GEOLOCATION_MAPP_SUCCESS = 'GET_GEOLOCATION_MAPP_SUCCESS'
export const GET_GEOLOCATION_MAPP_FAILURE = 'GET_GEOLOCATION_MAPP_FAILURE'

export const GET_GEOLOCATION_CHARTDRIVE_REQUEST = 'GET_GEOLOCATION_CHARTDRIVE_REQUEST'
export const GET_GEOLOCATION_CHARTDRIVE_SUCCESS = 'GET_GEOLOCATION_CHARTDRIVE_SUCCESS'
export const GET_GEOLOCATION_CHARTDRIVE_FAILURE = 'GET_GEOLOCATION_CHARTDRIVE_FAILURE'