export const GET_ASSORTMENT_CHARTBRAND_REQUEST = 'GET_ASSORTMENT_CHARTBRAND_REQUEST'
export const GET_ASSORTMENT_CHARTBRAND_SUCCESS =' GET_ASSORTMENT_CHARTBRAND_SUCCESS'
export const GET_ASSORTMENT_CHARTBRAND_FAILURE = 'GET_ASSORTMENT_CHARTBRAND_FAILURE'

export const GET_ASSORTMENT_TABLE_REQUEST = 'GET_ASSORTMENT_TABLE_REQUEST'
export const GET_ASSORTMENT_TABLE_SUCCESS = 'GET_ASSORTMENT_TABLE_SUCCESS'
export const GET_ASSORTMENT_TABLE_FAILURE = 'GET_ASSORTMENT_TABLE_FAILURE'

export const GET_ASSORTMENT_BRAND_TABLE_REQUEST = 'GET_ASSORTMENT_BRAND_TABLE_REQUEST'
export const GET_ASSORTMENT_BRAND_TABLE_SUCCESS = 'GET_ASSORTMENT_BRAND_TABLE_SUCCESS'
export const GET_ASSORTMENT_BRAND_TABLE_FAILURE = 'GET_ASSORTMENT_BRAND_TABLE_FAILURE'

export const GET_ASSORTMENT_CHARTDN_REQUEST = 'GET_ASSORTMENT_CHARTDN_REQUEST'
export const GET_ASSORTMENT_CHARTDN_SUCCESS = 'GET_ASSORTMENT_CHARTDN_SUCCESS'
export const GET_ASSORTMENT_CHARTDN_FAILURE = 'GET_ASSORTMENT_CHARTDN_FAILURE'

export const CHANGE_LOCAL_PERIOD = 'CHANGE_LOCAL_PERIOD'