export const GET_CHART_TITLE_DATA_REQUEST = 'GET_CHART_TITLE_DATA_REQUEST'
export const GET_CHARTTITLE_DATA_SUCCESS = 'GET_CHARTTITLE_DATA_SUCCESS'
export const GET_CHARTTITLE_DATA_FAILURE = 'GET_CHARTTITLE_DATA_FAILURE'

export const GET_CHARTIMAGE_DATA_REQUEST = 'GET_CHARTIMAGE_DATA_REQUEST'
export const GET_CHARTIMAGE_DATA_SUCCESS = 'GET_CHARTIMAGE_DATA_SUCCESS'
export const GET_CHARTIMAGE_DATA_FAILURE = 'GET_CHARTIMAGE_DATA_FAILURE'

export const GET_CHARTLEGAL_DATA_REQUEST = 'GET_CHARTLEGAL_DATA_REQUEST'
export const GET_CHARTLEGAL_DATA_SUCCESS = 'GET_CHARTLEGAL_DATA_SUCCESS'
export const GET_CHARTLEGAL_DATA_FAILURE = 'GET_CHARTLEGAL_DATA_FAILURE'

export const GET_PRODUCT_TABLE_REQUEST = 'GET_PRODUCT_TABLE_REQUEST'
export const GET_PRODUCT_TABLE_SUCCESS = 'GET_PRODUCT_TABLE_SUCCESS'
export const GET_PRODUCT_TABLE_FAILURE = 'GET_PRODUCT_TABLE_FAILURE'

