export const GET_MEDIA_TABLE_REQUEST = 'GET_MEDIA_TABLE_REQUEST'
export const GET_MEDIA_TABLE_SUCCESS = 'GET_MEDIA_TABLE_SUCCESS'
export const GET_MEDIA_TABLE_FAILURE = 'GET_MEDIA_TABLE_FAILURE'

export const GET_CHART_DATA_REQUEST = 'GET_CHART_DATA_REQUEST'
export const GET_MEDIA_CHART_DATA_SUCCESS = 'GET_MEDIA_CHART_DATA_SUCCESS'
export const GET_CHART_DATA_FAILURE = 'GET_CHART_DATA_FAILURE'

export const GET_FCHART_DATA_REQUEST = 'GET_FCHART_DATA_REQUEST'
export const GET_FCHART_DATA_SUCCESS = 'GET_FCHART_DATA_SUCCESS'
export const GET_FCHART_DATA_FAILURE = 'GET_FCHART_DATA_FAILURE'

export const GET_MEDIATIMELINE_DATA_REQUEST = 'GET_MEDIATIMELINE_DATA_REQUEST'
export const GET_MEDIATIMELINE_DATA_SUCCESS = 'GET_MEDIATIMELINE_DATA_SUCCESS'
export const GET_MEDIATIMELINE_DATA_FAILURE = 'GET_FMEDIATIMELINE_DATA_FAILURE'

export const CHANGE_LOCAL_PERIOD = 'CHANGE_LOCAL_PERIOD'
export const CHANGE_MANUFACTURER_GROUP = 'CHANGE_MANUFACTURER_GROUP'
export const CHANGE_FCHART_MANUFACTURER_GROUP = 'CHANGE_FCHART_MANUFACTURER_GROUP'