export const GET_STABLE_REQUEST = 'GET_STABLE_REQUEST'
export const GET_STABLE_SUCCESS = 'GET_STABLE_SUCCESS'
export const GET_STABLE_FAILURE = 'GET_STABLE_FAILURE'

export const GET_CTABLE_REQUEST = 'GET_CTABLE_REQUEST'
export const GET_CTABLE_SUCCESS = 'GET_CTABLE_SUCCESS'
export const GET_CTABLE_FAILURE = 'GET_CTABLE_FAILURE'

export const GET_CHARTS_REQUEST = 'GET_CHARTS_REQUEST'
export const GET_CHARTS_SUCCESS = 'GET_CHARTS_SUCCESS'
export const GET_CHARTS_FAILURE = 'GET_CHARTS_FAILURE'

export const GET_CHARTC_REQUEST = 'GET_CHARTC_REQUEST'
export const GET_CHARTC_SUCCESS = 'GET_CHARTC_SUCCESS'
export const GET_CHARTC_FAILURE = 'GET_CHARTC_FAILURE'

export const GET_CHARTFB_REQUEST = 'GET_CHARTFB_REQUEST'
export const GET_CHARTFB_SUCCESS = 'GET_CHARTFB_SUCCESS'
export const GET_CHARTFB_FAILURE = 'GET_CHARTFB_FAILURE'

export const GET_FTABLE_REQUEST = 'GET_FTABLE_REQUEST'
export const GET_FTABLE_SUCCESS = 'GET_FTABLE_SUCCESS'
export const GET_FTABLE_FAILURE = 'GET_FTABLE_FAILURE'