export const GET_PRICE_TABLE_REQUEST = 'GET_PRICE_TABLE_REQUEST'
export const GET_PRICE_TABLE_SUCCESS = 'GET_PRICE_TABLE_SUCCESS'
export const GET_PRICE_TABLE_FAILURE = 'GET_PRICE_TABLE_FAILURE'

export const GET_CHART_DATA_REQUEST = 'GET_CHART_DATA_REQUEST'
export const GET_PRICE_CHART_DATA_SUCCESS = 'GET_PRICE_CHART_DATA_SUCCESS'
export const GET_CHART_DATA_FAILURE = 'GET_CHART_DATA_FAILURE'
