export const GET_SALES_TABLE_REQUEST = 'GET_SALES_TABLE_REQUEST'
export const GET_SALES_TABLE_SUCCESS = 'GET_SALES_TABLE_SUCCESS'
export const GET_SALES_TABLE_FAILURE = 'GET_SALES_TABLE_FAILURE'

export const GET_SALES_STABLE_REQUEST = 'GET_SALES_STABLE_REQUEST'
export const GET_SALES_STABLE_SUCCESS = 'GET_SALES_STABLE_SUCCESS'
export const GET_SALES_STABLE_FAILURE = 'GET_SALES_STABLE_FAILURE'

export const GET_SALES_CHARTBRAND_REQUEST = 'GET_SALES_CHARTBRAND_REQUEST'
export const GET_SALES_CHARTBRAND_SUCCESS = 'GET_SALES_CHARTBRAND_SUCCESS'
export const GET_SALES_CHARTBRAND_FAILURE = 'GET_SALES_CHARTBRAND_FAILURE'

export const GET_SALES_CHARTVOL_REQUEST = 'GET_SALES_CHARTVOL_REQUEST'
export const GET_SALES_CHARTVOL_SUCCESS = 'GET_SALES_CHARTVOL_SUCCESS'
export const GET_SALES_CHARTVOL_FAILURE = 'GET_SALES_CHARTVOL_FAILURE'

export const GET_SALES_CHARTBRANDPROMO_REQUEST = 'GET_SALES_CHARTBRANDPROMO_REQUEST'
export const GET_SALES_CHARTBRANDPROMO_SUCCESS = 'GET_SALES_CHARTBRANDPROMO_SUCCESS'
export const GET_SALES_CHARTBRANDPROMO_FAILURE = 'GET_SALES_CHARTBRANDPROMO_FAILURE'

export const CHANGE_LOCAL_PERIOD = 'CHANGE_LOCAL_PERIOD'
