export const GET_RATING_TABLE_REQUEST = 'GET_RATING_TABLE_REQUEST'
export const GET_RATING_TABLE_SUCCESS = 'GET_RATING_TABLE_SUCCESS'
export const GET_RATING_TABLE_FAILURE = 'GET_RATING_TABLE_FAILURE'

export const GET_BBCHART_DATA_REQUEST = 'GET_BBCHART_DATA_REQUEST'
export const GET_BBCHART_DATA_SUCCESS = 'GET_BBCHART_DATA_SUCCESS'
export const GET_BBCHART_DATA_FAILURE = 'GET_BBCHART_DATA_FAILURE'

export const GET_BTIME_DATA_REQUEST = 'GET_BTIME_DATA_REQUEST'
export const GET_BTIME_DATA_SUCCESS = 'GET_BTIME_DATA_SUCCESS'
export const GET_BTIME_DATA_FAILURE = 'GET_BTIME_DATA_FAILURE'